### ISSUE TITLE
Not running on postman

### ISSUE THREAD

**Issue by kenkaigu** [adgsenpai/LoadSheddingAPI#1]
Hello 

thanks for publishing this wonderful work,  However when i try to run some examples on postman...i get an error

 `<html>
    <head>
        <title>Request Rejected</title>
    </head>
    <body>The requested URL was rejected. Please consult with your administrator.
        <br>
        <br>Your support ID is: bla bla bla
        <br>
        <br>
        <a href='javascript:history.back();'>[Go Back]</a>
    </body>
</html>`

**Comment by adgsenpai** [comment]
> Hello
> 
> thanks for publishing this wonderful work, However when i try to run some examples on postman...i get an error
> 
> ` <title>Request Rejected</title> The requested URL was rejected. Please consult with your administrator. Your support ID is: bla bla bla [Go Back]
> 
> `

Hi Kenkaigu,

as you know this API is powered by the Official Eskom API.
There are some endpoints today which is taken down by Eskom themselves.
I think some of the routes are deprecated. I do apologize for the inconvenience.

Otherwise if you discover any official endpoints and would like me to implement with the module. Just shout out here and ill had a easy way to get it working in Python with minimum code.

Best Regards
Ashlin Darius Govindasamy
